name: admin-console

services:
  db:
    image: postgres:17
    container_name: admin-console-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin_console
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
    container_name: admin-console-web
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/admin_console?schema=public
      NEXTAUTH_URL: http://localhost
      NEXTAUTH_SECRET: please-change-me
    depends_on:
      - db
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: admin-console-nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  admin-console-db-data:
